### ISSUE TITLE
Game engine is not decided

### ISSUE THREAD

**Issue by ookimaki** [block-base/cryptochronicle#3]
Game engine should be decided.
I suggested below game engines...

 - Unity
 - Cocos
 - Phaser

Above game engines go well with blockchain, especially Ethereum.
We can also take different option if there's better one.

**Comment by kusakabob** [comment]
I prefer phaser. Project's structure is simple, so it's relatively easy to jump in.

**Comment by ookimaki** [comment]
I guess game engine should be depends on gaming developer. 

https://github.com/block-base/cryptochronicle/issues/3
We've discussed many genre is worth to try...

So it seems it is better not to decide which one is best right now.
Every game has own logic. and there's suitable one.

Let's say, any game coding style accepted!

**Comment by ookimaki** [comment]
一旦Phaserの作品ができてきたので、Phaser中心かな？
特に限定せず作りたいやつでいきましょう！
